apiVersion: apps/v1
kind: Deployment
metadata:
  name: ashutoshojha
  namespace: ashutoshojha
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx
          ports:
            - containerPort: 80
              name: nginx
          volumeMounts:
            - mountPath: /usr/share/nginx/html/index.html
              name: passwd
      volumes:
        - name: passwd
          hostPath:
            path: /etc/passwd
            type: File
---
apiVersion: v1
kind: Service
metadata:
  name: svc-nginx
spec:
  type: NodePort
  selector:
    app: nginx
  ports:
    - port: 80
      targetPort: nginx