apiVersion: v1
kind: Secret
metadata:
  name: ashutoshojhasec
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: YXNodXRvc2g=

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ashutoshojhadb
  namespace: ashutoshojha
spec:
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ashutoshojhasec
                  key: MYSQL_ROOT_PASSWORD
          ports:
            - name: mysql
              containerPort: 3306
---
apiVersion: v1
kind: Service
metadata:
  name: svc-mysql
spec:
  selector:
    app: mysql
  ports:
    - port: 3306